= RES-Q db package
Marie Jankujova <jankujova.marie@fnusa.cz>
:doctype: article
:toc: true
:toclevels: 1
:imagesdr: assets/images
:source-highlighter: rouge
:rouge-style: Colorful
:revnumber: 1.0
:revdate: June 1, 2020
:revmark: {doctitle}
:description: RES-Q db package 
:keywords: RES-Q db
:icons: font
:setlinks: 
//:pdf-them

== Description
This is the package that has been created for the RES-Q project. After the project started to grow up, we needed to generate feedbacks for the users. This packaged is used as one feedback in the form of presentations and tables with calculated statistics. 

== Installation
We haven't used `pip` so far therefore copy the folder `resqdb` into `site-packages` of your python installation.

Install the following packages as well:

[source,python]
----
pip3 install pandas, numpy, logging, xlsxwriter, pytz, scipy, psycopg2, zipfile, python-pptx, statistics
----

We've made also one modification of the `python-pptx` script. This modification will set that each label is shown on category axis, the default is that label is shown only for each second label. There are two options how to fix this:

. Copy the `resqdb\tmp\xmlwriter.py` into `python-pptx\chart` folder.

. Modify the file `python-pptx\chart\xmlwriter.py`. We will modify the setting for the classes `BarChartXmlWriter` and `LineChartXmlWriter`. Into the function `cat_ax_xml` add the line `'<c:tickLblSkip val="1"/>\n'` into `return` function. I always put it after the line `<c:tickLblPos val="nextTo"/>`.

I prefer the last option because there can be during months/years the updated in the python-pptx package and if we copy the old file we can break something or loose updates. 

== Usage
=== Get data 
[source,python]
----
from resqdb.Connection import Connection # <1>

c = Connection(nprocess=2) # <2>
c = Connection(nprocess=2, data='qasc') # <3>

dictdb_df = c.df # <4>

preprocessed_data = c.preprocessed_data # <5>
----
<1> Import Connection from the Connection module.
<2> Create Connection object. You can provide number of processed (`nprocess`) as argument but to be honest it doesn't work well. Or you can run it without argument and run it with 1 process. If create connection object without `data` argument the data from `resq_mix`, `ivttby_mix` and `thailand` are preprocessed. 
<3> This is example of the way how to provide argument to say which data you would like to obtain from the database. Another options is `atalaia` and `africa`. 
<4> The raw data can be accessed with property `df`. 
<5> The preprocessed data can be accessed with property `preprocessed_data`. I strongly recommend save this data as `csv` with `,` (comma) as a seperator.

=== Filter data
This script uses the preprocessed data obtained from the Connection object or provided as argument. I provided examples of how to filter data by dates (<<filter_by_dates>>) or country (<<filter_by_country>>), but you can combine it and filter by country and dates in one run. Create object without any other arguments will filter data by DISCHARGE_DATE column. There are cases when the data has to be filtered by HOSPITAL_DATE or include all patients who have HOSPITAL_DATE or DISCHARGE_DATE in the date range. Both these options are mentioned in the following code (<<filter_by_dates>>).

[#filter_by_dates]
==== Filter data by date
The following code is example how to filter data for the date range. The date is filtered based on discharge dates. 

[source,python]
----
from resqdb.Calculation import FilterDataset # <1>
from datetime import datetime # <2>

date1 = datetime(2019, 3, 1) # <3>
date2 = datetime(2019, 3, 31) # <4>

fobj = FilterDataset(df=preprocessed_data, date1=date1, date2=date2) # <5>
fobj = FilterDataset(df=preprocessed_data, date1=date1, date2=date2, column="HOSPITAL_DATE") # <6>
fobj = FilterDataset(df=preprocessed_data, date1=date1, date2=date2, by_columns=True) # <7>

df = fobj.fdf # <8>
----
<1> Import FilterDataset from the Calculation module.
<2> Import datetime object from datetime module.
<3> Set first date that should be included in the dataset. 
<4> Set last date that should be included in the dataset. 
<5> Create new FilterDataset object where `df` are preprocessed data, `date1` and `date2` are ranges of the dates. 
<6> Create new FilterDataset object where the data will be filtered by hospital date. 
<7> Create new FilterDataset object where the data will be filtered by both columns, hospital date and discharge date. 
<8> The filtered result is stored in property called `fdf`. 

[#filter_by_country]
==== Filter data by country
The following code is example how to filter data by country. 

[source,python]
----
from resqdb.Calculation import FilterDataset # <1>
from datetime import datetime # <2>

fobj = FilterDataset(df=preprocessed_data, country='CZ') # <3>
df = fobj.fdf # <4>

----
<1> Import FilterDataset from the Calculation module.
<2> Import datetime object from datetime module.
<3> Create a new object FilterDataset with preprocessed data and country code as argument. 
<4> The filtered result is stored in property called `fdf`. 

=== Generate preprocessed data
[source,python]
----
from resqdb.FormatData import GeneratePreprocessedData # <1>

GeneratePreprocessedData(df=df, report=report_type, quarter=quarter_name) # <2>
----
<1> Import `GeneratePreprocessedData` from the resqdb package. 
<2> Create new object that will generate prerpocessed data. Provide preprocessed data as argument `df` and other additional names that will be used in the name of the file, such as `report` and `quarter`. 

=== Compute statistics
[source,python]
---- 
from resqdb.Calculation import ComputeStats # <1>

comp_df = ComputeStats(df=df, comparison=False, patient_limit=min_tpts, period=quarter_name, raw_data=raw_df) # <2>

stats_df = comp_df._return_stats() # <3>
----
<1> Import `ComputeStats` from the resqdb package. 
<2> Create new object `ComputeStats`. Provide preprocessed data (`df`), raw dataframe by which I mean the preprocessed data with all data that were not filtered yet (`raw_df`). 
<3> Obtainer calculated statistics from the object. 